### ISSUE TITLE
[Metrics] - Pipeline has hardcoded author for commit 

### ISSUE THREAD

**Issue by safo-bora** [safo-bora/tests_demo#7]
Grafana Reports - http://35.176.58.38:3000/public-dashboards/a9ec57ea6b934c8ab14f46fec32e00f9?orgId=1&refresh=5s

https://github.com/safo-bora/tests_demo/blob/main/.github/workflows/ci-configuration.yaml#L42
https://github.com/safo-bora/tests_demo/blob/main/.github/workflows/ci-configuration.yaml#L139

<img width="1200" alt="Screenshot 2024-07-08 at 09 59 38" src="https://github.com/safo-bora/tests_demo/assets/4173393/e6c35809-4dc9-4ab7-9a22-b04158582bc6">

**Comment by ShulhaVitalii** [comment]
Fixed in https://github.com/safo-bora/tests_demo/pull/8
![image](https://github.com/safo-bora/tests_demo/assets/107625988/31daf439-1880-4312-a98d-fcc4e2b79bb3)

**Comment by safo-bora** [comment]
Thanks! @ShulhaVitalii
